/* This file is automatically generated by configure */
/* DO NOT EDIT MANUALLY */

#ifndef CONFIG_H
#define CONFIG_H

#define SCUMM_LITTLE_ENDIAN
#define SCUMM_NEED_ALIGNMENT


#undef LINUPY

/* Data types */
typedef unsigned char byte;
typedef unsigned int uint;
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
typedef signed char int8;
typedef signed short int16;
typedef signed int int32;

/* Libs */
#undef USE_VORBIS
#undef USE_TREMOR
#undef USE_FLAC
#undef USE_MAD
#undef USE_ALSA
#undef USE_ZLIB
#undef USE_MPEG2
#undef USE_FLUIDSYNTH
#undef USE_MT32EMU

/* Whether we should use i386 assembly routines */
#undef USE_NASM

/* Plugin settings */


#endif /* CONFIG_H */
