# -------- Generated by configure -----------

CXX := arm-uclinux-elf-g++
CXXFLAGS :=   -g -ansi -W -Wno-unused-parameter
LIBS +=  common/libcommon.a ../libs/ttk/libs/SDL/libSDL.a -lstdc++ -lpthread
RANLIB := ranlib
INSTALL := install
AR := ar cru
MKDIR := mkdir -p
ECHO := printf
CAT := cat
RM := rm -f
RM_REC := rm -f -r
ZIP := zip -q
CP := cp
WIN32PATH=C:/scummvm
AOS4PATH=Games:ScummVM_Snapshot

BACKEND := ipod
MODULES +=  backends/ipod
MODULE_DIRS += 
EXEEXT := 
NASM := 
NASMFLAGS := 

PREFIX := /usr/local
BINDIR := /usr/local/bin
MANDIR := /usr/local/man


HAVE_GCC3 = 1
# HAVE_NASM = 1
# DISABLE_SCUMM = 1
# DISABLE_SCUMM_7_8 = 1
# DISABLE_HE = 1
# DISABLE_SIMON = 1
# DISABLE_SKY = 1
# DISABLE_SWORD1 = 1
# DISABLE_SWORD2 = 1
# DISABLE_QUEEN = 1
# DISABLE_KYRA = 1
# DISABLE_SAGA = 1
# DISABLE_GOB = 1
#DISABLE_LURE = 1
#DISABLE_CINE = 1
#DISABLE_AGI = 1
# USE_MT32EMU = 1

# DISABLE_HQ_SCALERS = 1
# DISABLE_SCALERS = 1

INCLUDES +=  -I../libs/ttk/sdlincludes
OBJS += 
DEFINES +=  -DUNIX -D_BSD_SOURCE -DIPOD -DDISABLE_HELP
LDFLAGS +=  -Wl,-elf2flt
